source("funkcje.R")
dane_stara_hala=unname(unlist(read.table("stara_hala.txt")))
dane_nowa_hala=unname(unlist(read.table("nowa_hala.txt")))
cat("Test Kolmogorowa-Lillieforsa dla danych starej hali:\n")
test_kolmogomorowa_lillieforsa(dane_stara_hala)
cat("Test Kolmogorowa-Lillieforsa dla danych nowej hali:\n")
test_kolmogomorowa_lillieforsa(dane_nowa_hala)