source("funkcje.R")
dane_stara_hala=unname(unlist(read.table("stara_hala.txt")))
dane_nowa_hala=unname(unlist(read.table("nowa_hala.txt")))
test_kolmogomorowa_lillieforsa(dane_stara_hala)
test_kolmogomorowa_lillieforsa(dane_nowa_hala)